services:
  - type: web
    name: shadow-goose-grant-portal
    runtime: node
    buildCommand: cd frontend && npm ci && npm run build
    startCommand: cd frontend && npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
    buildFilter:
      paths:
        - frontend/**
      ignoredPaths:
        - frontend/src/**/*.test.*
        - frontend/src/**/*.spec.* 