services:
  # Backend API Service
  - type: web
    name: sge-grant-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NOTIFICATION_EMAIL
        value: admin@shadowgoose.com
      - key: EMAIL_FROM
        value: noreply@shadowgoose.com

  # Frontend React Service  
  - type: web
    name: sge-grant-frontend
    env: node
    buildCommand: cd sge-grant-dashboard && npm install && npm run build
    startCommand: cd sge-grant-dashboard && npm run preview
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://sge-grant-backend.onrender.com 