services:
  # Backend API Service
  - type: web
    name: grant-iq-pro-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /health

  # Frontend Static Site
  - type: static
    name: grant-iq-pro-frontend
    buildCommand: cd sge-grant-dashboard && npm install && npm run build
    staticPublishPath: ./sge-grant-dashboard/dist 