services:
  # Backend API Service
  - type: web
    name: grant-iq-pro-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NOTIFICATION_EMAIL
        value: admin@grantiqpro.com
      - key: EMAIL_FROM
        value: noreply@grantiqpro.com

  # Frontend React Service  
  - type: web
    name: grant-iq-pro-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd sge-grant-dashboard && npm ci && npm run build
    startCommand: cd sge-grant-dashboard && npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: https://grant-iq-pro-backend.onrender.com 